server:
  port: 8084
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/config
eureka:
  instance:
    hostname: config-server
    instance-id: config-server:8084
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/  #注册中心地址



